name: Feature request
description: Suggest an idea for this project
title: "[Feature request]: "
labels: ["enhancement"]
assignees:
  - purple-emily
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Related to a problem?
    description: Is your feature request related to a problem? Please describe.
  validations:
    required: false
- type: textarea
  attributes:
    label: Your solution
    description: Describe the solution you'd like.
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternative ideas
    description: Describe alternatives you've considered
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context or screenshots about the feature request here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
